-- Rollback: Drop permissions table
DROP INDEX IF EXISTS idx_roles_tenant_id;
DROP INDEX IF EXISTS idx_roles_name;
DROP INDEX IF EXISTS idx_user_roles_user_id;
DROP INDEX IF EXISTS idx_user_roles_role_id;
DROP INDEX IF EXISTS idx_permissions_resource;
DROP INDEX IF EXISTS idx_permissions_name;
DROP INDEX IF EXISTS idx_role_permissions_role_id;
DROP TABLE IF EXISTS permissions;
