#!/bin/bash
# ==============================================================================
# Generate .ai-review.yaml from environment variables
# 
# Usage in GitLab CI:
#   - bash scripts/generate-ai-review-config.sh
#
# Environment Variables:
#   AI_REVIEW_MAX_FILES        - Maximum files to review (default: 10)
#   AI_REVIEW_MAX_FILE_SIZE    - Max file size in bytes (default: 150000)
#   AI_REVIEW_MAX_TOKENS       - LLM max tokens (default: 15000)
#   AI_REVIEW_TEMPERATURE      - LLM temperature (default: 0.3)
#   AI_REVIEW_MAX_COMMENTS     - Max inline comments (default: 30)
#   CI_PROJECT_PATH            - GitLab project path (auto)
#   CI_MERGE_REQUEST_IID       - MR number (auto)
# ==============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
MAX_FILES="${AI_REVIEW_MAX_FILES:-10}"
MAX_FILE_SIZE="${AI_REVIEW_MAX_FILE_SIZE:-150000}"
MAX_TOKENS="${AI_REVIEW_MAX_TOKENS:-15000}"
TEMPERATURE="${AI_REVIEW_TEMPERATURE:-0.3}"
MAX_COMMENTS="${AI_REVIEW_MAX_COMMENTS:-30}"

# Validate required variables
if [ -z "$LLM__HTTP_CLIENT__API_URL" ]; then
    echo -e "${RED}ERROR: LLM__HTTP_CLIENT__API_URL is required${NC}"
    exit 1
fi

if [ -z "$OLLAMA_PROXY_API_KEY" ]; then
    echo -e "${RED}ERROR: OLLAMA_PROXY_API_KEY is required${NC}"
    exit 1
fi

if [ -z "$GITLAB_API_TOKEN" ]; then
    echo -e "${RED}ERROR: GITLAB_API_TOKEN is required${NC}"
    exit 1
fi

if [ -z "$CI_PROJECT_ID" ]; then
    echo -e "${RED}ERROR: CI_PROJECT_ID is required${NC}"
    exit 1
fi

if [ -z "$CI_MERGE_REQUEST_IID" ]; then
    echo -e "${RED}ERROR: CI_MERGE_REQUEST_IID is required${NC}"
    exit 1
fi

if [ -z "$CI_SERVER_URL" ]; then
    echo -e "${RED}ERROR: CI_SERVER_URL is required (should be set by GitLab CI)${NC}"
    exit 1
fi

if [ -z "$LLM__META__MODEL" ]; then
    echo -e "${YELLOW}WARNING: LLM__META__MODEL not set, using default: deepseek-coder:6.7b${NC}"
    LLM__META__MODEL="deepseek-coder:6.7b"
fi

echo -e "${GREEN}Generating .ai-review.yaml with configuration:${NC}"
echo ""
echo "LLM Settings:"
echo "  API URL: $LLM__HTTP_CLIENT__API_URL"
echo "  Model: $LLM__META__MODEL"
echo "  Max Tokens: $MAX_TOKENS"
echo "  Temperature: $TEMPERATURE"
echo ""
echo "GitLab Settings:"
echo "  Server: $CI_SERVER_URL"
echo "  Project: $CI_PROJECT_ID"
echo "  MR: $CI_MERGE_REQUEST_IID"
echo ""
echo "Review Policy:"
echo "  Max Files: $MAX_FILES"
echo "  Max File Size: $MAX_FILE_SIZE bytes"
echo "  Max Comments: $MAX_COMMENTS"
echo ""

# Generate .ai-review.yaml
cat > .ai-review.yaml <<EOF
# ==============================================================================
# AI Review Configuration (Generated by GitLab CI)
# ==============================================================================
# 
# This file is auto-generated by scripts/generate-ai-review-config.sh
# DO NOT edit manually - changes will be overwritten
# 
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Pipeline: $CI_PIPELINE_URL
# ==============================================================================

# ------------------------------------------------------------------------------
# LLM Configuration
# ------------------------------------------------------------------------------
llm:
  provider: OPENAI  # Ollama-OpenAI Proxy compatibility
  
  meta:
    model: ${LLM__META__MODEL}
    max_tokens: ${MAX_TOKENS}
    temperature: ${TEMPERATURE}
  
  http_client:
    api_url: ${LLM__HTTP_CLIENT__API_URL}
    api_token: ${OLLAMA_PROXY_API_KEY}
    timeout: 300  # 5 minutes

# ------------------------------------------------------------------------------
# VCS Configuration (GitLab)
# ------------------------------------------------------------------------------
vcs:
  provider: GITLAB
  
  pipeline:
    project_id: ${CI_PROJECT_ID}
    merge_request_id: ${CI_MERGE_REQUEST_IID}
  
  http_client:
    api_url: ${CI_SERVER_URL}
    api_token: ${GITLAB_API_TOKEN}
    timeout: 120

# ------------------------------------------------------------------------------
# Review Policy
# ------------------------------------------------------------------------------
policy:
  # Include only Go files and important configs
  include:
    - "**/*.go"
    - "*.yaml"
    - "*.yml"
    - "Dockerfile"
    - "go.mod"
  
  # Exclude tests, vendor, generated code
  exclude:
    - "**/*_test.go"
    - "**/vendor/**"
    - "**/testdata/**"
    - "**/*.pb.go"
    - "**/*_gen.go"
    - "**/bin/**"
    - "**/dist/**"
    - "**/data/**"
    - "**/logs/**"
    - "**/.git/**"
    - "**/node_modules/**"
    - "**/web/assets/**"
    - "**/docs/**"
    - "**/BACKLOG/**"
  
  # Limits (configured via CI variables)
  max_file_size: ${MAX_FILE_SIZE}  # ${MAX_FILE_SIZE} bytes
  max_files: ${MAX_FILES}  # Maximum files in one review

# ------------------------------------------------------------------------------
# Modes Configuration
# ------------------------------------------------------------------------------
modes:
  inline:
    enabled: true
    max_comments: ${MAX_COMMENTS}
    min_severity: low
  
  summary:
    enabled: true
    include_statistics: true
    include_recommendations: true
  
  context:
    enabled: true
    analyze_dependencies: true
    check_breaking_changes: true

# ------------------------------------------------------------------------------
# Prompts (Go-specific)
# ------------------------------------------------------------------------------
prompts:
  inline: |
    You are an expert Go code reviewer for Ollama-OpenAI Proxy project.
    
    ⚠️ CRITICAL: Return ONLY valid JSON array. NO markdown, NO code blocks, NO explanations.
    
    Format (EXACTLY):
    [
      {
        "file": "path/to/file.go",
        "line": 10,
        "comment": "Issue description with fix suggestion"
      }
    ]
    
    Start with [ and end with ]. Do NOT wrap in \`\`\`json.
    
    Review this code change for:
    
    🔴 CRITICAL (must fix):
    - Goroutine leaks (missing context cancellation, WaitGroup.Done)
    - Race conditions (concurrent access without synchronization)
    - SQL injection vulnerabilities
    - Unhandled errors (especially in defer, goroutines)
    - Resource leaks (unclosed connections, files)
    
    🟡 IMPORTANT (should fix):
    - False sharing in concurrent structures
    - Inefficient database queries (N+1)
    - Missing context usage
    - Poor error handling (errors not wrapped with %w)
    - Performance issues
    
    💡 SUGGESTIONS:
    - Code organization improvements
    - Better naming conventions
    
    Language: Russian
    Be concise, provide line numbers, suggest fixes.
  
  summary: |
    Provide Go code review summary in Russian.
    
    ⚠️ IMPORTANT: Return plain text, NOT JSON.
    
    Structure:
    
    ## Общая оценка
    - Качество: ⭐⭐⭐⭐⭐ (1-5)
    - Готовность: ✅ READY / ⚠️ CONDITIONAL / ❌ NEEDS WORK
    
    ## Критичные проблемы
    - [List with file:line references]
    
    ## Важные замечания
    - [List issues]
    
    ## Предложения
    - [Optional improvements]
    
    ## Что сделано хорошо ✅
    - [Positive points]
    
    ## Чек-лист
    - [ ] Тесты
    - [ ] OpenAI API совместимость
    - [ ] Конфигурация обратно совместима
    - [ ] Миграция БД
    - [ ] Документация
    - [ ] Нет breaking changes
    
    Be constructive and educational.

# ------------------------------------------------------------------------------
# Artifacts
# ------------------------------------------------------------------------------
artifacts:
  enabled: false  # Disabled in CI
  output_dir: .ai-review-artifacts

# ------------------------------------------------------------------------------
# Logging
# ------------------------------------------------------------------------------
logging:
  level: INFO
  format: structured
  log_llm_requests: false
  log_llm_responses: false

# ==============================================================================
# End of Generated Configuration
# ==============================================================================
EOF

echo -e "${GREEN}✓ .ai-review.yaml generated successfully${NC}"
echo ""

# Validate the file exists and is not empty
if [ ! -s .ai-review.yaml ]; then
    echo -e "${RED}ERROR: Generated .ai-review.yaml is empty${NC}"
    exit 1
fi

# Show file info
echo -e "${GREEN}File info:${NC}"
ls -lh .ai-review.yaml
echo ""

# Show first 10 lines
echo -e "${GREEN}Preview (first 15 lines):${NC}"
head -n 15 .ai-review.yaml
echo "..."
echo ""

echo -e "${GREEN}✓ Configuration ready for AI review${NC}"

